namespace SpriteKind {
    export const door = SpriteKind.create()
    export const key = SpriteKind.create()
}
controller.anyButton.onEvent(ControllerButtonEvent.Pressed, function () {
    animation.runImageAnimation(
    mySprite,
    [img`
        . . . . . . f f f f . . . . . . 
        . . . . f f f 2 2 f f f . . . . 
        . . . f f f 2 2 2 2 f f f . . . 
        . . f f f e e e e e e f f f . . 
        . . f f e 2 2 2 2 2 2 e e f . . 
        . . f e 2 f f f f f f 2 e f . . 
        . . f f f f e e e e f f f f . . 
        . f f e f b f 4 4 f b f e f f . 
        . f e e 4 1 f d d f 1 4 e e f . 
        . . f e e d d d d d d e e f . . 
        . . . f e e 4 4 4 4 e e f . . . 
        . . e 4 f 2 2 2 2 2 2 f 4 e . . 
        . . 4 d f 2 2 2 2 2 2 f d 4 . . 
        . . 4 4 f 4 4 5 5 4 4 f 4 4 . . 
        . . . . . f f f f f f . . . . . 
        . . . . . f f . . f f . . . . . 
        `,img`
        . . . . . . . . . . . . . . . . 
        . . . . . . f f f f . . . . . . 
        . . . . f f f 2 2 f f f . . . . 
        . . . f f f 2 2 2 2 f f f . . . 
        . . f f f e e e e e e f f f . . 
        . . f f e 2 2 2 2 2 2 e e f . . 
        . f f e 2 f f f f f f 2 e f f . 
        . f f f f f e e e e f f f f f . 
        . . f e f b f 4 4 f b f e f . . 
        . . f e 4 1 f d d f 1 4 e f . . 
        . . . f e 4 d d d d 4 e f e . . 
        . . f e f 2 2 2 2 e d d 4 e . . 
        . . e 4 f 2 2 2 2 e d d e . . . 
        . . . . f 4 4 5 5 f e e . . . . 
        . . . . f f f f f f f . . . . . 
        . . . . f f f . . . . . . . . . 
        `,img`
        . . . . . . f f f f . . . . . . 
        . . . . f f f 2 2 f f f . . . . 
        . . . f f f 2 2 2 2 f f f . . . 
        . . f f f e e e e e e f f f . . 
        . . f f e 2 2 2 2 2 2 e e f . . 
        . . f e 2 f f f f f f 2 e f . . 
        . . f f f f e e e e f f f f . . 
        . f f e f b f 4 4 f b f e f f . 
        . f e e 4 1 f d d f 1 4 e e f . 
        . . f e e d d d d d d e e f . . 
        . . . f e e 4 4 4 4 e e f . . . 
        . . e 4 f 2 2 2 2 2 2 f 4 e . . 
        . . 4 d f 2 2 2 2 2 2 f d 4 . . 
        . . 4 4 f 4 4 5 5 4 4 f 4 4 . . 
        . . . . . f f f f f f . . . . . 
        . . . . . f f . . f f . . . . . 
        `,img`
        . . . . . . . . . . . . . . . . 
        . . . . . . f f f f . . . . . . 
        . . . . f f f 2 2 f f f . . . . 
        . . . f f f 2 2 2 2 f f f . . . 
        . . f f f e e e e e e f f f . . 
        . . f e e 2 2 2 2 2 2 e f f . . 
        . f f e 2 f f f f f f 2 e f f . 
        . f f f f f e e e e f f f f f . 
        . . f e f b f 4 4 f b f e f . . 
        . . f e 4 1 f d d f 1 4 e f . . 
        . . e f e 4 d d d d 4 e f . . . 
        . . e 4 d d e 2 2 2 2 f e f . . 
        . . . e d d e 2 2 2 2 f 4 e . . 
        . . . . e e f 5 5 4 4 f . . . . 
        . . . . . f f f f f f f . . . . 
        . . . . . . . . . f f f . . . . 
        `],
    500,
    false
    )
})
sprites.onOverlap(SpriteKind.Player, SpriteKind.door, function (sprite, otherSprite) {
    game.gameOver(true)
})
sprites.onOverlap(SpriteKind.Player, SpriteKind.key, function (sprite, otherSprite) {
    mySprite3 = sprites.create(img`
        ................................................
        ................................................
        ................................................
        ................................................
        ................................................
        ................................................
        ................................................
        ................................................
        ................................................
        ................................................
        ................................................
        ................................................
        ................................................
        ................................................
        ................................................
        ................................................
        ................................................
        ................................................
        ................................................
        ................................................
        ................................................
        ................................................
        ................................................
        ................................................
        ................................................
        ................................................
        ................................................
        ................................................
        ................................................
        .................444444444444444................
        .................111111111111111................
        ................6666666666666666................
        ................6222222222222226................
        ...............6e22222222222222261c.............
        ...............6e22222222222222261c.............
        ...............6f222effffff2222266c.............
        ..............66f22ffffffffff22266c.............
        ..............66f22ffffffffff22266c.............
        ..............66f22222222222222266c.............
        ...............6e22222222222222266c.............
        ...............6e22222222222222266c.............
        ...............6e2222222222f222266c.............
        ...............6e2222222222ffff266c.............
        ...............6f2222222222f22f266c.............
        ...............6f2222222222eff2266c.............
        ...............6f2222222222e222266c.............
        ...............6f2222222222e222266c.............
        ...............6e2222222222e222266c.............
        `, SpriteKind.door)
    sprites.destroy(mySprite4)
    mySprite3.setPosition(32, 21)
})
sprites.onOverlap(SpriteKind.Player, SpriteKind.Enemy, function (sprite, otherSprite) {
    game.gameOver(false)
})
let mySprite3: Sprite = null
let mySprite4: Sprite = null
let mySprite: Sprite = null
scene.setBackgroundImage(img`
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    .................................................................................ffffff.........................................................................
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    .............................fffff...............................................ffffff....................................ffffff...............................
    .............................fffff...............................................ffffff....................................ffffff...............................
    ......................................fffffff....................................ffffff....................................ffffff...............................
    ......................................fffffff....................................ffffff....................................ffffff...............................
    ......................................fffffff....................................ffffff....................................ffffff...............................
    ......................................fffffff....................................ffffff....................................ffffff...............................
    ......................................fffffff....................................ffffff....................................ffffff...............................
    ......................................fffffff....................................ffffff....................................ffffff...............................
    ......................................fffffff....................................ffffff....................................ffffff...............................
    ......................................fffffff....................................ffffff....................................ffffff...............................
    ......................................fffffff....................................ffffff....................................ffffff...............................
    ......................................fffffff....................................ffffff....................................ffffff...............................
    ......................................fffffff....................................ffffff....................................ffffff...............................
    ......................................fffffff....................................ffffff....................................ffffff...............................
    ......................................fffffff....................................ffffff....................................ffffff...............................
    ......................................fffffff....................................ffffff....................................ffffff...............................
    ......................................fffffff....................................ffffff....................................ffffff...............................
    ......................................fffffff....................................ffffff....................................ffffff...............................
    ......................................fffffff....................................ffffff....................................ffffff...............................
    ......................................fffffff....................................ffffff....................................ffffff...............................
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ......................................fffffff....................................ffffff....................................ffffff...............................
    ......................................fffffff....................................ffffff....................................ffffff...............................
    ......................................fffffff....................................ffffff....................................ffffff...............................
    ......................................fffffff....................................ffffff....................................ffffff...............................
    ......................................fffffff....................................ffffff....................................ffffff...............................
    ......................................fffffff....................................ffffff....................................ffffff...............................
    ......................................fffffff....................................ffffff....................................ffffff...............................
    ......................................fffffff....................................ffffff....................................ffffff...............................
    ......................................fffffff....................................ffffff....................................ffffff...............................
    ......................................fffffff....................................ffffff....................................ffffff...............................
    ......................................fffffff....................................ffffff....................................ffffff...............................
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff..............
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff..............
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ......................................fffffff....................................ffffff....................................ffffff..............fffffffffffffffff
    ......................................fffffff....................................ffffff....................................ffffff...............................
    ......................................fffffff....................................ffffff....................................ffffff...............................
    ......................................fffffff....................................ffffff....................................ffffff...............................
    ......................................fffffff....................................ffffff....................................ffffff...............................
    ......................................fffffff....................................ffffff....................................ffffff...............................
    ......................................fffffff....................................ffffff....................................ffffff...............................
    f222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222
    f222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222
    f222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222
    f222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222
    f222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222
    f222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222
    f222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222dddddddddddddd2222222
    f222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222dddddddddddddd2222222
    fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffddddddddddddddfffffff
    ....................................fffffffff...................................fffffff....................................ffffffff........dddddddddddddd.......
    ....................................fffffffff...................................fffffff....................................ffffffff........dddddddddddddd.......
    ....................................fffff.......................................fffffff....................................ffffffff........ddddd....ddddd.......
    ....................................fffff.......................................fffffff....................................ffffffff........ddddd....ddddd.......
    ....................................fffff.......................................fffffff....................................ffffffff........ddddd....ddddd.......
    ....................................fffff.......................................ffffff.....................................ffffffff........ddddd....ddddd.......
    ....................................fffff.......................................ffffff.....................................ffffffff........ddddd....ddddd.......
    ....................................fffff.......................................ffffff.....................................ffffffff........ddddd....ddddd.......
    ....................................fffff.......................................ffffff.....................................ffffffff........ddddd....ddddd.......
    ....................................fffff.......................................ffffff.....................................ffffffff........ddddd....ddddd.......
    ....................................fffff.......................................ffffff.....................................ffffffff........dddddddddddddd.......
    .ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffddddddddddddddfffffff
    .ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffddddddddddddddfffffff
    .ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffddddddddddddddfffffff
    .ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffddddddddddddddfffffff
    .ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffddddddddddddddfffffff
    .ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffddddddddddddddfffffff
    .ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffddddddddddddddfffffff
    .ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffddddddddddddddfffffff
    ....................................fffff.......................................ffffff.....................................ffffffff........ddddd....ddddd.......
    ....................................fffff.......................................ffffff.....................................ffffffff........ddddd....ddddd.......
    ....................................fffff.......................................ffffff.....................................ffffffff........ddddd....ddddd.......
    ....................................fffff.......................................ffffff.....................................ffffffff........ddddd....ddddd.......
    ....................................fffff.......................................ffffff.....................................ffffffff........ddddd....ddddd.......
    ....................................fffff.......................................ffffff.....................................ffffffff........ddddd....ddddd.......
    ....................................fffff.......................................ffffff.....................................ffffffff........ddddd....ddddd.......
    ....................................fffff.......................................ffffff.....................................ffffffff........ddddd....ddddd.......
    ....................................fffff.......................................ffffff.....................................ffffffff........ddddd....ddddd.......
    ....................................fffff.......................................ffffff.....................................ffffffff........ddddd....ddddd.......
    ....................................fffff.......................................ffffff.....................................ffffffff........ddddd....ddddd.......
    ....................................fffff.......................................ffffff.....................................ffffffff........ddddd....ddddd.......
    ....................................fffff.......................................ffffff.....................................ffffffff........ddddd....ddddd.......
    ....................................fffff.......................................ffffff.....................................ffffffff........ddddd....ddddd.......
    ....................................fffff.......................................ffffff.....................................ffffffff........dddddddddddddd.......
    ....fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffddddddddddddddfffffff
    ....fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffddddddddddddddfffffff
    ....fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffddddddddddddddfffffff
    ....fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffddddddddddddddfffffff
    ....fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffddddddddddddddfffffff
    ....................................fffff.......................................ffffff.....................................ffffffff........dddddddddddddd.......
    ....................................fffff.......................................ffffff.....................................ffffffff........ddddd....ddddd.......
    ....................................fffff.......................................ffffff.....................................ffffffff........ddddd....ddddd.......
    ....................................fffff.......................................ffffff.....................................ffffffff........ddddd....ddddd.......
    ....................................fffff.......................................ffffff.....................................ffffffff........dddddddddddddd.......
    ....................................fffff.......................................ffffff.....................................ffffffff........dddddddddddddd.......
    ....................................fffff.......................................ffffff.....................................ffffffff........dddddddddddddd.......
    `)
scene.setBackgroundColor(13)
mySprite = sprites.create(img`
    . . . . . . f f f f . . . . . . 
    . . . . f f f 2 2 f f f . . . . 
    . . . f f f 2 2 2 2 f f f . . . 
    . . f f f e e e e e e f f f . . 
    . . f f e 2 2 2 2 2 2 e e f . . 
    . . f e 2 f f f f f f 2 e f . . 
    . . f f f f e e e e f f f f . . 
    . f f e f b f 4 4 f b f e f f . 
    . f e e 4 1 f d d f 1 4 e e f . 
    . . f e e d d d d d d e e f . . 
    . . . f e e 4 4 4 4 e e f . . . 
    . . e 4 f 2 2 2 2 2 2 f 4 e . . 
    . . 4 d f 2 2 2 2 2 2 f d 4 . . 
    . . 4 4 f 4 4 5 5 4 4 f 4 4 . . 
    . . . . . f f f f f f . . . . . 
    . . . . . f f . . f f . . . . . 
    `, SpriteKind.Player)
mySprite.setPosition(140, 95)
controller.moveSprite(mySprite)
let mySprite2 = sprites.create(img`
    ................................................
    ................................................
    ................................................
    ................................................
    ................................................
    ................................................
    ................................................
    ................................................
    ................................................
    ................................................
    ................................................
    ................................................
    ................................................
    ................................................
    ................................................
    ................................................
    ................................................
    ................................................
    ................................................
    ................................................
    ................................................
    ................................................
    ................................................
    ................................................
    ................................................
    ................................................
    ................................................
    ................................................
    ................................................
    .................444444444444444................
    .................111111111111111................
    ................6666666666666666................
    ................6eeeeeeeeeeeeee6................
    ...............6e4e44e44e44e44ee61c.............
    ...............6e4e44e44e44e44ee61c.............
    ...............6f4e4effffffe44ee66c.............
    ..............66f4effffffffff4ee66c.............
    ..............66f4effffffffffeee66c.............
    ..............66f4eeeeeeeeeeeeee66c.............
    ...............6e4e44e44e44e44ee66c.............
    ...............6e4e44e44e44e44ee66c.............
    ...............6e4e44e44e44feeee66c.............
    ...............6e4e44e44e44ffffe66c.............
    ...............6f4e44e44e44f44fe66c.............
    ...............6f4e44e44e44effee66c.............
    ...............6f4e44e44e44e44ee66c.............
    ...............6f4e44e44e44e44ee66c.............
    ...............6e4e44e44e44e44ee66c.............
    `, SpriteKind.Player)
mySprite2.setPosition(140, 95)
let prison_guard_3 = sprites.create(img`
    . . . . 2 2 2 2 2 e . . . . . . 
    . . . 2 2 2 2 d 2 2 e . . . . . 
    . . e 2 2 2 2 2 2 2 e . . . . . 
    . . e 2 2 2 2 2 2 2 e . . . . . 
    . . e 2 2 2 2 2 e f f c c . . . 
    . . e e 2 2 e f f f f b c . . . 
    . e e e f e 2 b f f f d c . . . 
    e e 2 2 d f 2 1 1 1 1 b c . . . 
    e e 2 2 d f e e c c c . . . . . 
    b 1 1 d e 2 2 e e c . . . . . . 
    . f f e 2 2 2 2 e . . . . . . . 
    . . f f d d 2 2 f f d d . . . . 
    . . f f d d e e f f d d . . . . 
    . . . f f f f . . . . . . . . . 
    . . e e e f f f . . . . . . . . 
    . . e e e e f f f . . . . . . . 
    `, SpriteKind.Enemy)
animation.runMovementAnimation(
prison_guard_3,
animation.animationPresets(animation.easeRight),
2000,
true
)
prison_guard_3 = sprites.create(img`
    . . . . 2 2 2 2 2 e . . . . . . 
    . . . 2 2 2 2 d 2 2 e . . . . . 
    . . e 2 2 2 2 2 2 2 e . . . . . 
    . . e 2 2 2 2 2 2 2 e . . . . . 
    . . e 2 2 2 2 2 e f f c c . . . 
    . . e e 2 2 e f f f f b c . . . 
    . e e e f e 2 b f f f d c . . . 
    e e 2 2 d f 2 1 1 1 1 b c . . . 
    e e 2 2 d f e e c c c . . . . . 
    b 1 1 d e 2 2 e e c . . . . . . 
    . f f e 2 2 2 2 e . . . . . . . 
    . . f f d d 2 2 f f d d . . . . 
    . . f f d d e e f f d d . . . . 
    . . . f f f f . . . . . . . . . 
    . . e e e f f f . . . . . . . . 
    . . e e e e f f f . . . . . . . 
    `, SpriteKind.Enemy)
animation.runMovementAnimation(
prison_guard_3,
animation.animationPresets(animation.easeDown),
5000,
true
)
let prison_guard_2 = sprites.create(img`
    . . . . 2 2 2 2 2 e . . . . . . 
    . . . 2 2 2 2 d 2 2 e . . . . . 
    . . e 2 2 2 2 2 2 2 e . . . . . 
    . . e 2 2 2 2 2 2 2 e . . . . . 
    . . e 2 2 2 2 2 e f f c c . . . 
    . . e e 2 2 e f f f f b c . . . 
    . e e e f e 2 b f f f d c . . . 
    e e 2 2 d f 2 1 1 1 1 b c . . . 
    e e 2 2 d f e e c c c . . . . . 
    b 1 1 d e 2 2 e e c . . . . . . 
    . f f e 2 2 2 2 e . . . . . . . 
    . . f f d d 2 2 f f d d . . . . 
    . . f f d d e e f f d d . . . . 
    . . . f f f f . . . . . . . . . 
    . . e e e f f f . . . . . . . . 
    . . e e e e f f f . . . . . . . 
    `, SpriteKind.Enemy)
prison_guard_2.setPosition(24, 107)
animation.runMovementAnimation(
prison_guard_2,
animation.animationPresets(animation.easeRight),
5000,
true
)
mySprite4 = sprites.create(img`
    . . . . . . . . . . . . . . . . 
    . . 5 5 5 5 5 . . . . . . . . . 
    . 5 . . . . . 5 . . . . . . . . 
    . 5 . . . . . 5 . . . . . . . . 
    . 5 . . . . . 5 . . . . . . . . 
    . 5 . . . . . 5 . . . . . . . . 
    . 5 . . . . . 5 . . . . . . . . 
    . . 5 5 5 5 5 . . . . . . . . . 
    . . . 5 5 . . . . . . . . . . . 
    . . . 5 5 5 5 . . . . . . . . . 
    . . . 5 5 . . . . . . . . . . . 
    . . . 5 5 5 5 5 . . . . . . . . 
    . . . 5 5 5 5 5 . . . . . . . . 
    . . . 5 5 . . . . . . . . . . . 
    . . . 5 5 5 5 5 . . . . . . . . 
    . . . 5 5 . . . . . . . . . . . 
    `, SpriteKind.key)
